### ISSUE TITLE
How to use Oxalis-AS4 with Oxalis 4.0.3 Tomcat

### ISSUE THREAD

**Issue by PeterOlausson65** [difi/Oxalis-AS4#1]
Are there any instructions on how to use the oxalis as4 jars with Oxalis running in a Tomcat 9?
I tried to add all jar files in the class path, but ended up with error
 java.lang.NoClassDefFoundError: javax/servlet/ServletContainerInitializer

The Tomcat Oxalis starts ok without the as4 jar files.

**Comment by PeterOlausson65** [comment]
Found some info on how to extend the oxalis.war file with own classes, and by packaging the oxalis.war with the Oxalis-AS4 package it seems as it starts ok.

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- Replace the following three values according to your preferences. -->
    <groupId>com.example.peppol</groupId>
    <artifactId>oxalis</artifactId>
    <version>1.0-SNAPSHOT</version>

    <!-- Create web archive. -->
    <packaging>war</packaging>

    <properties>
        <!-- Replace with 4.0.3 or newer. -->
        <oxalis.version>4.0.3</oxalis.version>
        <oxalis-as4.version>4.1.0-SNAPSHOT</oxalis-as4.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>no.difi.oxalis</groupId>
            <artifactId>oxalis-war</artifactId>
            <version>${oxalis.version}</version>
            <classifier>classes</classifier>
        </dependency>
        <dependency>
            <groupId>no.difi.oxalis</groupId>
            <artifactId>oxalis-as4</artifactId>
            <version>${oxalis-as4.version}</version>
        </dependency>
        <!-- Any other extensions or libraries to be included. -->
    </dependencies>

    <build>
        <!-- Resulting file as oxalis.war. -->
        <finalName>oxalis</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>2.1.1</version>
                <configuration>
                    <!-- Allow building without web.xml. -->
                    <failOnMissingWebXml>false</failOnMissingWebXml>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
```

**Comment by FrodeBjerkholt** [comment]
Great - It seems like you solved the problem. Then I assume it is fine to close this issue?

**Comment by GaitBoxman** [comment]
Hi Frode,
not really, I managed to include AS4 into TC 9 based setup after about a day of trial and error by eventually including the build of AS4 into the main oxalis 4.0.3. build, and than updating the pom.xml that builds the oxalis.4.0.3.war file with the dependency. But that is way out of line with what you guys have been trying to establish with the extensions setup. I mean, you even moved the AS/2 to extensions.. So what we really need is some good documentation on how to build the AS4 module and deploy it as an extension to our TC 9/ oxalis403 environment, and then some documentation on how to update the configuration, e.g. so we are aware that you added a truststore dependency that also needs to be placed and referenced. My first idea was to build AS4 separately and drop in my plugins folder, but oxalis does not even notice it that way.. 
-- Gait.

**Comment by evenos** [comment]
We have added an example of how to deploy Oxalis with AS4 in the [RC4 release ](https://github.com/difi/Oxalis-AS4/releases/tag/4.1.0-RC4)
