### ISSUE TITLE
Extrange "No matching party found" issue during CEF Connectivity Test

### ISSUE THREAD

**Issue by gozus19p** [difi/Oxalis-AS4#108]
Hello Oxalis team!

I am facing off an issue doing CEF Connectivity Test (Static Discovery AS4 Connectivity test).
In order to be more specific at the moment I am processing outbound testing, I'm trying to send a payload to CEF.

I set up Oxalis configuration as you described in the documentation, but I get a FAULT_IN with cause "No matching party found".
I checked sender and recipient values and they are exactly what CEF sent me when I started the testing process.

- sender: **ceftestparty89gw**
- recipient: **cefsupportgw**

I attach here an example of SOAP envelope that goes out and a SOAP fault that comes in as a response.

[files.zip](https://github.com/difi/Oxalis-AS4/files/4298850/files.zip)

CEF support told me that this could be an AS4 policy incompatibility issue, but I am not sure about that.
As a consequent test I tried to replace Oxalis' policy with the one CEF sent me, but I get the following stack trace:

_java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: **Algorithm suite "Basic128GCMSha256MgfSha256" is not registered**
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at eu.sendregning.oxalis.Main.main(Main.java:225)
Caused by: java.lang.IllegalArgumentException: Algorithm suite "Basic128GCMSha256MgfSha256" is not registered
        at (...)
        at no.difi.oxalis.as4.util.PolicyService.getPolicy(PolicyService.java:63)
        at no.difi.oxalis.as4.util.PolicyService.getPolicy(PolicyService.java:46)
        at no.difi.oxalis.as4.util.PolicyService.getPolicy(PolicyService.java:39)_

I ask them to check if participant identifiers are correct but they answered positively.

I am using the following Oxalis' versions:
- **Oxalis 4.1.1 release**;
- **Oxalis-AS4 4.1.7 release**.

Could you, please, help me understand from where does the issue come from?
Thank you in advance, I wish you a good day.

**Comment by FrodeBjerkholt** [comment]
There should be no need to replace the security profile as long as you are using the correct configuration. Can you show me your oxalis.conf for the outbound and the command line you are executing, please?

**Comment by gozus19p** [comment]
Thanks for the fast feedback, Frode.

Sure, I attach here my [oxalis-conf.zip](https://github.com/difi/Oxalis-AS4/files/4298940/oxalis-conf.zip).

You can find below the command I am running.

> java -DOXALIS_HOME="C:\Users\MGozzi\.oxalis" -classpath "standalone/*;as4/*" eu.sendregning.oxalis.Main -cert "C:\Users\MGozzi\.oxalis\cefconnectivitytest\ceftestparty89gw.crt" -f payload.xml --protocol peppol-transport-as4-v2_0 -u "http://40.115.23.114:8080/domibus/services/msh"

I installed Oxalis standalone as explained [here](https://github.com/difi/Oxalis-AS4/blob/master/docs/installation/standalone.md).

**Comment by FrodeBjerkholt** [comment]
First you need to use ./cefsupportgw.cer
It it always the certificate of the receiving AP that you should use.

I also see that I got a slightly different URL from CEF. Try adding the ?domain=static parameter.

```bash
java -DOXALIS_HOME=/c/dev/cef/.oxalis \
  -classpath "standalone/*;as4/*" \
  eu.sendregning.oxalis.Main \
  -cert ./cefsupportgw.cer \
  -f cef-connectivity.xml \
  --protocol peppol-transport-as4-v2_0 \
  -u "http://40.115.23.114:8080/domibus/services/msh?domain=static"
```

**Comment by gozus19p** [comment]
Ok, I was using the wrong certificate.
I extracted the alias "cefsupportgw" from the truststore that CEF gave me and I also changed the URI as you suggested.
I successfully passed this test phase.

Thank you so much for your support, have a nice weekend!
