### ISSUE TITLE
Conformance tests GITB Send an invoice or credit note as an AS4 message.

### ISSUE THREAD

**Issue by sanderverhoeven** [difi/Oxalis-AS4#115]
Hi,

when sending an message toward domibus-gitb i am receiving the following error message:

Payload: 
`<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope"><env:Header><eb:Messaging xmlns:eb="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/" env:mustUnderstand="true"><eb:SignalMessage><eb:MessageInfo><eb:Timestamp>2020-03-30T14:50:36.414Z</eb:Timestamp><eb:MessageId>1596603e-0e6a-46ca-b02f-39211c7b3c0a@domibus.eu</eb:MessageId><eb:RefToMessageId>de7cb87b-9451-41a5-8ae0-5cdaa0aceed0@host.docker.internal</eb:RefToMessageId></eb:MessageInfo><eb:Error category="CONTENT" errorCode="EBMS:0003" origin="ebMS" refToMessageInError="de7cb87b-9451-41a5-8ae0-5cdaa0aceed0@host.docker.internal" severity="failure" shortDescription="ValueInconsistent"><eb:Description xml:lang="">Although the message document is well formed and schema valid, some element/attribute value is inconsistent either with the content of other element/attribute, or with the processing mode of the MSH, or with the normative requirements of the ebMS specification.</eb:Description><eb:ErrorDetail>No matching party found</eb:ErrorDetail></eb:Error></eb:SignalMessage></eb:Messaging></env:Header><env:Body><env:Fault><env:Code><env:Value>env:Receiver</env:Value></env:Code><env:Reason><env:Text xml:lang="en">An error occurred while processing your request. Please check the message header for more details.</env:Text></env:Reason></env:Fault></env:Body></env:Envelope>`

this is the Test File I'm sending:

set attachment: 
[PeppolBisEDI.zip](https://github.com/difi/Oxalis-AS4/files/4403751/PeppolBisEDI.zip)

It is taking the gitb-engine name from the certificate as receiving party.
[error-log.txt](https://github.com/difi/Oxalis-AS4/files/4403756/error-log.txt)

<ns2:To>
						<ns2:PartyId type="urn:oasis:names:tc:ebcore:partyid-type:unregistered">**gitb-engine**</ns2:PartyId>
						<ns2:Role>http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/responder</ns2:Role>
					</ns2:To>

Comment from cef-einvoicing-support:

Hi Sander,

For your information, GITB access point name is “domibus-gitb” and the truststore certificate of the access point alias is “gitb-engine”. 
So you can add gitb-engine certificate in Cert property of your request and try with recipient name as “domibus-gitb”. 

               <ns:To>
                  <ns:PartyId type="urn:oasis:names:tc:ebcore:partyid-type:unregistered">domibus-gitb</ns:PartyId>
                  <ns:Role>http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/responder</ns:Role>
               </ns:To>

**Comment by FrodeBjerkholt** [comment]
Which conformance test is this? The cef-conformance test type is only for performing the basic CEF connectivity test. If so, you should follow the tutorial. To find out whar the Domibus server complains about, you have to ask the ones running the Domibus server.

**Comment by sanderverhoeven** [comment]
This is the test for The exchange of electronic invoices using the Universal Business Language (UBL) 2.1 and Cross Industry Invoice (CII) syntaxes. At https://www.itb.ec.europa.eu/cef/itb/app,

I have followed the tutorial but changed the action according to 
[AS4_User_Soapui-project_invoicing_test.zip](https://github.com/difi/Oxalis-AS4/files/4407320/AS4_User_Soapui-project_invoicing_test.zip)

**Comment by FrodeBjerkholt** [comment]
We do not support this out of the box. Oxalis is made for the Peppol network, so to make such a conformance test to work, changes are needed.

**Comment by Magnus91** [comment]
Hi Sander,
Did you find a solution to this problem? I currently have the same issue.

**Comment by sanderverhoeven** [comment]
I uses domibus to send and receive these files.
