### ISSUE TITLE
peppol testbed error on #5 Outbound Testbed sends to testing AP

### ISSUE THREAD

**Issue by vincentpwnz00r** [difi/Oxalis-AS4#122]
I have installed oxalis and oxalis as4 using tomcat. domain.com/as4 and domain.com/as4/status  successfully loads. However, after i tried to run the testbed, I have faced error in #5 OUTBOUND Testbed sends to testing AP. domain is SSL-ed and i have a valid testing AP cert

Transaction (with instance identifier PSG000383-15-20200521T044635) to testing AP failed to be delivered. Error; Failed to send message.

Why would this happen?

**Comment by FrodeBjerkholt** [comment]
I am not sure. You should ask support at the Open Peppol Testbed, if they can see something in their logs. You should also check the logs of your AP to see if you see something in there or not.

**Comment by vincentpwnz00r** [comment]
Hi Frode, thank you for the reply

I have received a reply from them 

**The transaction cannot be completed because your AP implementation is responding with an HTTP 500 error during the transaction. You should be able to detect that your AP is responding with an error.

Furthermore, you seem to return the following error specifics:

<eb:Error category="Content" errorCode="EBMS:0004" origin="ebms" refToMessageInError="455c4ee2-097d-429e-8f5e-13f23101ede2@ip-10-10-136-128.eu-west-1.compute.internal" severity="error" shortDescription="Other">
	<eb:ErrorDetail>Error processing payload input stream cause: /var/peppol</eb:ErrorDetail>
</eb:Error>**

Which folder will i be able to find the logs of my AP? Thank you

**Comment by vincentpwnz00r** [comment]
This was an issue with tomcat initialisation (there were 2 different tomcats in my system and since resolved this), i have restarted tomcat and its working as intended now
