### ISSUE TITLE
Oxalis not working after renewing certificate 

### ISSUE THREAD

**Issue by KnyGoo** [difi/Oxalis-AS4#123]
Hi,

We should renew our peppol certificate soon because it will expire, but after including the new certificate testbed fails with following message. (We have an issue when receiving documents.)

For AS2
Transaction (with instance identifier *****) to testing AP failed to be delivered. Error; Unable to verify content of MDN using certificate provided by SMP..

Stacktrace:
No stacktrace but something wrong with MDN.

For AS4
Transaction (with instance identifier *****) to testing AP failed to be delivered. Error; Failed to send message.

Stacktrace:
org.apache.wss4j.dom.processor.EncryptedKeyProcessor.getPrivateKey(EncryptedKeyProcessor.java:266)org.apache.wss4j.common.crypto.Merlin.getPrivateKey(Merlin.java:624)
Caused by: org.apache.wss4j.common.ext.WSSecurityException: Cannot find key for certificate

Seems like something is wrong with the new certificate? Certificate is working to connect to testbed. Old certificate still works. Anyone an idea?

With kind regards,

Kenny

**Comment by aksamit** [comment]
Hi Kenny,

please register a support case with OpenPeppol Operating Office and we will have a look at this: https://openpeppol.atlassian.net/servicedesk/customer/portal/1

I suspect your Test Bed configuration might be configured with your old TEST AP certificate and we need to adjust this manually to reflect the details of your new TEST AP certificate. There is a new version of the Test Bed that will handle this situation automatically, but that version is still undergoing QA and I cannot present an expected date for release at this moment.

Best regards,

Mikael Aksamit
2nd line support, OpenPEPPOL Operating Office

**Comment by KnyGoo** [comment]
Hi Mikael,

Thank you for your prompt reply. This fixed our problem!

Kind regards,

Kenny
