### ISSUE TITLE
fatal: [BR-CL-11]-Any registration identifier identification scheme identifier MUST be coded using one of the ISO 6523 ICD list.

### ISSUE THREAD

**Issue by sanderverhoeven** [difi/Oxalis-AS4#126]
We cannot send a file from :
cause: Payload invalid, 'iso6523-actorid-upis::0106:0000000' to 'iso6523-actorid-upis::9920:0000000' using 'TransportProtocol{AS4}'

[BR-CL-11]-Any registration identifier identification scheme identifier MUST be coded using one of the ISO 6523 ICD list. fatal: [BR-CL-11]-Any registration identifier identification scheme identifier MUST be coded using one of the ISO 6523 ICD list. cause: fatal: [BR-CL-11]-Any registration identifier identification scheme identifier MUST be coded using one of the ISO 6523 ICD list. fatal: [BR-CL-11]-Any registration identifier identification scheme identifier MUST be coded using one of the ISO 6523 ICD list.
        at no.difi.oxalis.as4.outbound.TransmissionResponseConverter.convert(TransmissionResponseConverter.java:56)
        at no.difi.oxalis.as4.outbound.As4MessageSender.invoke(As4MessageSender.java:106)

Can we disable validation when sending a file over the test network?

**Comment by FrodeBjerkholt** [comment]
It is the receiving access point that responds with the error message, so it will not help to disable validation on your side.

**Comment by sanderverhoeven** [comment]
Hi Frode, thank you. I have requested to update there Oxalis AP.

**Comment by sanderverhoeven** [comment]
9920 is supported as endpoint id, but not as party identifier. changing the party identifier fixed the issue.
