### ISSUE TITLE
PEPPOL AS4 incorrect Signature Algorithm vs AS4 spec

### ISSUE THREAD

**Issue by clancger** [difi/Oxalis-AS4#14]
Signature Algorithm

Used in OpenPEPPOL testbed...
http://www.w3.org/2009/xmlenc11#rsa-oaep

Should be as below
PMode[].Security.X509.Signature.Algorithm parameter MUST be set to  
http://www.w3.org/2001/04/xmldsig-more#rsa-sha256 

https://ec.europa.eu/cefdigital/wiki/display/CEFDIGITAL/eDelivery+AS4+-+1.14

**Comment by ekorra** [comment]
We agree that rsa-sha256 is to be used, and should be the one used by Oxalis.
Can you confirm that you are testing against Oxalis-AS4 RC5 version (commit https://github.com/difi/Oxalis-AS4/commit/9af603f0e0bae7fabce199ab747e9eb3ce76ad4b)

**Comment by clancger** [comment]
THe version we tested agianst is the Oxalis version inside the OpenPEPPOL testbed, ( when we did the testing in March), no way for me to know which version that is
