### ISSUE TITLE
PEPPOL AS4 MimeType issue

### ISSUE THREAD

**Issue by clancger** [difi/Oxalis-AS4#16]
The MimeType specified EncryptedData Element in the AS4 Testbed message is “application/octet-stream”and should be  “application/gzip” as below.

The PartInfo element in the message header that relates to a compressed payload part MUST have an eb:Property element with its name attribute set to the value CompressionType. The content type of a compressed payload part MUST be application/gzip.

https://ec.europa.eu/cefdigital/wiki/display/CEFDIGITAL/eDelivery+AS4+-+1.14#eDeliveryAS4-1.14-Example

**Comment by evenos** [comment]
Sorry for the late reply.

We are currently focussing on passing the CEF conformance but will incorporate this issue in that work.

**Comment by clancger** [comment]
Dear Difi team, Any updates please?

**Comment by ekorra** [comment]
This issue is solved in the [RC6 release](https://github.com/difi/Oxalis-AS4/releases/tag/4.1.0-RC6)
Where the CEF conformance test is pased with annotations
