### ISSUE TITLE
ModeProvider - Production as detected mode

### ISSUE THREAD

**Issue by KnyGoo** [difi/Oxalis-AS4#19]
While using production certificate with Oxalis docker image I see the following in startup log:
11:29:31.117 [main] INFO  n.d.v.peppol.security.ModeDetector - Detection error (TEST): Validation of subject principal(CN) failed.
11:29:33.394 [main] INFO  n.d.oxalis.commons.mode.ModeProvider - Detected mode: PRODUCTION

As soon I add the AS4-plugin as extension, detection mode 'TEST' is logged while this should be 'PRODUCTION':
11:32:34.369 [main] INFO  n.d.oxalis.commons.mode.ModeProvider - Detected mode: test

Any idea what's going wrong here? Seems like Oxalis is working correctly, but wrong mode is logged. Mode is detected by certificate.

**Comment by mindweaver** [comment]
I have the same issue!

**Comment by senikk** [comment]
I've been told its just "info" about it have checked if the certificate is a test certificate so its nothing to worry about this info message.

**Comment by evenos** [comment]
This issue is resolved in [RC9](https://github.com/difi/Oxalis-AS4/releases/tag/4.1.0-RC9)
