### ISSUE TITLE
Certification of Oxalis as an AS4 compliant solution

### ISSUE THREAD

**Issue by intesa-oxalis** [difi/Oxalis-AS4#2]
Hi all, 

we had just a look at the AS4 compliant solutions that are listed under this link:
https://ec.europa.eu/cefdigital/wiki/display/CEFDIGITAL/CEF+eInvoicing+Conformance+Testing
--
Will Oxalis pass the e-Delivery conformance test? Will Oxalis also be listed in this page? When? 

Thank you,

**Comment by ekorra** [comment]
We are currently working on passing the OpenPEPPOL required part of this test. Once this is done Oxalis will be added to the list with a disclaimer
