### ISSUE TITLE
Incorrect iso6523 handling in AS4 Header? - MessageProperties / OriginalSender & finalrecipient

### ISSUE THREAD

**Issue by clancger** [difi/Oxalis-AS4#20]
In the AS4 message header received on an inbound message from the OpenPEPPOL testbed, under "MessageProperties", "OriginalSender" and "finalrecipient" are expressed as shown below...

<eb:MessageProperties>
         <eb:Property name="originalSender">0088:tbcntrl00002</eb:Property>
         <eb:Property name="finalRecipient">0088:5050689000018</eb:Property>
</eb:MessageProperties>

I believe that since type is an optional parameter, you should add the full identifier in the value, including the `iso6523-actorid-upis`

![image (3)](https://user-images.githubusercontent.com/1429765/61133252-5dbdba00-a4bd-11e9-8be9-082172cd4785.png)

**Comment by clancger** [comment]
The suggested correct layout for this is
`iso6523-actorid-upis::0088:value` or to be more generic `meta-scheme::scheme:valuue'


eb:MessageProperties
<eb:Property name="originalSender">iso6523-actorid-upis::0088:tbcntrl00002</eb:Property>
<eb:Property name="finalRecipient">iso6523-actorid-upis::0088:5050689000018</eb:Property>
</eb:MessageProperties>

(per info from Philip Helger)

**Comment by evenos** [comment]
We will add the full identfier to _originalSender_ and _finalRecipient_.

**Comment by clancger** [comment]
Thanks Even

**Comment by mstennie** [comment]
Hi guys,

Is it present in the specification? If so, can you share a link to it?
Thanks
Mathieu Stennier
Babelway/Tradeshift
