### ISSUE TITLE
Can't find released artifacts in public maven repo

### ISSUE THREAD

**Issue by sanathwijewardhana** [difi/Oxalis-AS4#21]
I need to use your latest release but couldn't find any published artifact for Oxalis-AS4. Any reason for this?

**Comment by jannewaren** [comment]
+1 for this. It would be really helpful if this AS4 library would be available in Maven repository like other Oxalis projects.

**Comment by ekorra** [comment]
The AS4 will be available in Maven reposistory when we have a production release

**Comment by jannewaren** [comment]
Now that there is https://github.com/difi/Oxalis-AS4/releases/tag/4.1.0 released, would it be possible to release this in Maven repository? It has a major difference in the way we build and deploy our services based on Oxalis.
