### ISSUE TITLE
Problem with extend oxalis 4.0.4 with as4 (tomcat)

### ISSUE THREAD

**Issue by mgu7** [difi/Oxalis-AS4#22]
I have a problem with extending the functionality of oxalis 4.0.4 by AS4 protocol (version with tomcat). When starting tomcat, an error appears:
SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more Filters failed to start. Full details will be found in the appropriate container log file,
SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Context [/ oxalis] startup failed due to previous errors

The main module causes the problem: oxalis-as4-4.1.0-SNAPSHOT.jar
Its removal allows you to start tomacat correctly without AS4 functionality.

Could I count on any suggestions to solve the problem.

Regards
Mietek Guja

**Comment by jannewaren** [comment]
First thing to do would be check the logs like it says?

>  Full details will be found in the appropriate container log file

Usually there are multiple logfiles stored somewhere under $CATALINA_HOME so find them and see what the actual error is. In my experience it's usually something wrong with the oxalis.conf - had this kind of a problem many times when trying something new.

**Comment by FrodeBjerkholt** [comment]
@mgu7 - Have you been able to get it to work or do you still have problems? To help we need some more information. Can you please attach some log files and the contents of  $CATALINA_BASE/conf/Catalina/localhost/oxalis.xml

**Comment by mgu7** [comment]
I resolved the problem, as you inform me the problem was in missing configuration lines in oxalis.conf. 
But the auxiliary lines needed for AS4 are not described in official documentation.

**Comment by FrodeBjerkholt** [comment]
Great that you were able to solve the problem. Which auxiliary lines did you add?

**Comment by mgu7** [comment]
lookup.locator.hostname
oxalis.truststore.path
oxalis.truststore.password
transport.as4_peppol_v1_to_v2_adapter (optionally)
and I should build truststore.jks

**Comment by FrodeBjerkholt** [comment]
Thanks. I will take a look at the documentation.
