### ISSUE TITLE
Ebms Receipts should also use BinarySecurityToken (PEPPOL Testbed issue)

### ISSUE THREAD

**Issue by clancger** [difi/Oxalis-AS4#23]
Ebms Receipts should also use BinarySecurityToken to provide the certificate used for signing.
Pls refer also to TICC-85

There appears to be a problem with the OpenPEPPOL testbed ebmsReceipts.  They do not include the signing certificate as a binary-security-token (BST).

It appears the BST in the main message is ok, but missing from the ebmsReceipt

Rune is already aware, per Philip Helger

**Comment by clancger** [comment]
https://openpeppol.atlassian.net/browse/TICC-85

**Comment by evenos** [comment]
We have implemented the change. It will be part of the next (pre-)release.
