### ISSUE TITLE
RC8 still needs lookup.locator.hostname to be set

### ISSUE THREAD

**Issue by senikk** [difi/Oxalis-AS4#26]
This is still an issue with Oxalis AS4 RC8. I can't get it work anymore without setting lookup.locator.hostname in my reference.conf file

![image](https://user-images.githubusercontent.com/400752/65038960-703af080-d951-11e9-9584-8e529a5895ce.png)

Since Oxalis AS4 RC8 also gives mode "test" instead of production could this be related? /ref #24

_Originally posted by @senikk in https://github.com/difi/Oxalis-AS4/issues/10#issuecomment-532185921_

**Comment by evenos** [comment]
We see that our original fix in RC8 was insufficient to resolve the issue. We are in the process of testing some additional changes to address this issue.

**Comment by evenos** [comment]
Thank you for your feed back. We have now released [RC9](https://github.com/difi/Oxalis-AS4/tree/4.1.0-RC9) that adresses this issue.
