### ISSUE TITLE
RC8 Connection timed out

### ISSUE THREAD

**Issue by senikk** [difi/Oxalis-AS4#27]
After switching to RC8 I've seen several times the instance of sending have stopped completely. The last time I checked the logs it took 17 minutes before the connection timed out and the instance again started to send.

Anyone seen the same?
Any solution?

13:31:27.495 [main] DEBUG org.apache.http.impl.conn.DefaultClientConnectionOperator - Connecting to xxx:443
13:48:46.185 [main] DEBUG org.apache.http.impl.conn.DefaultClientConnection - Connection org.apache.http.impl.conn.DefaultClientConnection@7bdbbdf closed
13:48:46.186 [main] INFO org.apache.http.impl.client.DefaultHttpClient - I/O exception (java.net.SocketException) caught when connecting to {s}->xxx:443: Connection timed out (Read failed)

**Comment by evenos** [comment]
It is difficult to address connection issues like this.
One suggestion i can make to reduce the inconvenience of sutch issues is altering the timeout settings in [Oxalis configuration](https://github.com/difi/oxalis/blob/master/doc/configuration.adoc) (see the HTTP section)
