### ISSUE TITLE
Problem with AS2 MDN when including AS4 module

### ISSUE THREAD

**Issue by emilbokenstrand** [difi/Oxalis-AS4#3]
Greetings,

I have a POM with the following snippet:

```
<dependency>
  <groupId>no.difi.oxalis</groupId>
  <artifactId>oxalis-war</artifactId>
  <version>4.0.3</version>
  <classifier>classes</classifier>
</dependency>
<dependency>
  <groupId>no.difi.oxalis</groupId>
  <artifactId>oxalis-as4</artifactId>
  <version>4.1.0-SNAPSHOT</version>
</dependency>
```

I test by sending files to myself. AS4 files seems to work but AS2 does not work fully when the AS4-module is included. I receive the file ok but the parsing of the MDN on the sending side goes wrong with following exception:

no.difi.oxalis.api.lang.OxalisTransmissionException: AS2 transmission failed : = 
 Received headers    Date: Tue, 08 Jan 2019 15:20:38 +0000  Message-Id: <1546960 
837777.1.1653001218.Oxalis@peppoltest>  Subject: AS2 message from Oxalis  MIME-V 
ersion: 1.0  Content-Type: multipart/signed; protocol="application/pkcs7-signatu 
re"; micalg=sha-1; boundary="----=_Part_0_1847832028.1546960837942"  Content-Len 
gth: 144650  as2-from: PSE000027  as2-to: PSE000027  disposition-notification-to 
: not.in.use@difi.no  dispositio                                                 
n-notification-options: signed-receipt-protocol=required,pkcs7-signature; signed 
-receipt-micalg=required,sha1  as2-version: 1.0  host: peppoltest.tyringe.com  c 
onnection: Keep-Alive  user-agent: Oxalis 4.0.3  accept-encoding: gzip,deflate       at no.difi.oxalis.as2.outbound.As2MessageSender.handleResponse(As2MessageSen
der.java:312)  at no.difi.oxalis.as2.outbound.As2MessageSender.sendHttpRequest(A
s2MessageSender.java:246)  at no.difi.oxalis.as2.outbound.As2MessageSender.send(
As2MessageSender.java:155)  at n                                                
o.difi.oxalis.as2.outbound.As2MessageSenderFacade.send(As2MessageSenderFacade.ja
va:58)  at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(Defau
ltTransmitter.java:149)  at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:106)

I have debugged this and it seems to be an issue with the encoding of the MDN-BodyPart on the receiving end.
On the bodypart with Content-Type=message/disposition-notification I get
Content-Transfer-Encoding=base64 when including the AS4-module
but I get
Content-Transfer-Encoding=7bit when NOT including it - and in this case all goes well!

In the case where I get base64 the content is actually not base64 making the parsing of the MDN from the sending side go into error.

This difference I believe is caused by geronimo-javamail_1.4_mail-1.8.4.jar which is included by the AS4-module (via cxf-rt-ws-securit). This jar has partly the same classes as mail-1.4.7.jar used by oxalis but with different code and including the as4-module makes the geronimo-classes being used (MimeMessage for example) making this error occur.

Please let me know if I need to clarify anything or if there is a trick to make this error disappear.

Best regards 

Emil

**Comment by FrodeBjerkholt** [comment]
Can you try the following change, please? Replace 

```xml
<dependency>
    <groupId>org.apache.cxf</groupId>
    <artifactId>cxf-rt-ws-security</artifactId>
    <version>3.2.2</version>
</dependency>
```

with this:

```xml
<dependency>
    <groupId>org.apache.cxf</groupId>
    <artifactId>cxf-rt-ws-security</artifactId>
    <version>3.2.2</version>
    <exclusions>
        <exclusion>
            <groupId>org.apache.geronimo.javamail</groupId>
            <artifactId>geronimo-javamail_1.4_mail</artifactId>
        </exclusion>
    </exclusions>
</dependency>

<dependency>
    <groupId>javax.mail</groupId>
    <artifactId>mail</artifactId>
    <version>1.4.7</version>
    <exclusions>
        <exclusion>
             <groupId>javax.activation</groupId>
             <artifactId>activation</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by ekorra** [comment]
As there is no replay to this question we will close this issue

**Comment by mindweaver** [comment]
Hi

I have the same problem. Where do I put those dependencies?
