### ISSUE TITLE
Issue installing RC9

### ISSUE THREAD

**Issue by Giovanna72** [difi/Oxalis-AS4#30]
Hi,
I've installed with success Oxalis 4.0.4 on Tomcat8 using the oxalis-war-4.0.4.war file released.

Following the README.txt file for AS4 RC9, I'm not able to find "ext" folder.
I've created the "ext" folder in the /opt/tomcat/webapps/oxalis/WEB-INF folder and put all the jars extracted from the AS4 RC9 zip.

Also I've created the oxalis.xml file in the Catalina/localhost folder and restarted tomcat service.
But no way to see the localhost:8080/as4 endpoint....

Could you please give me help on this problem?
Thank you and regards!

**Comment by Giovanna72** [comment]
solved.

**Comment by linuxdrw** [comment]
Hi Giovanna
I have the same problem, how did you solve it?
Thank you

**Comment by linuxdrw** [comment]
Solved for me too, adding deployXML="true" in Host definition in the server.xml tomcat config file

**Comment by Giovanna72** [comment]
Hi linuxdrw,
I've solved copying all the as4 jar into the lib folder of oxalis webapp and restarting Tomcat.
This is one way...the other is following putting the as4 jars into a separate folder and creating the "oxalis.xml" file into the "Catalina/localhost" folder of Tomcat server as written in the Oxalis-AS4 Installation guide.

Bye

**Comment by linuxdrw** [comment]
> Hi linuxdrw,
> I've solved copying all the as4 jar into the lib folder of oxalis webapp and restarting Tomcat.
> This is one way...the other is following putting the as4 jars into a separate folder and creating the "oxalis.xml" file into the "Catalina/localhost" folder of Tomcat server as written in the Oxalis-AS4 Installation guide.
> 
> Bye

Thank you!
