### ISSUE TITLE
JVM wide proxy settings not honored like in AS2

### ISSUE THREAD

**Issue by open-gdsn** [difi/Oxalis-AS4#44]
When ' certifying'  our AS4 endpoint using 4.1.0-RC10 we ran into the issue that the AS4 extension does not honour the jvm wide proxy settings  like the AS2 extension does. 

Can this be corrected?

**Comment by PeterOlausson65** [comment]
Are you using -Dhttps.proxyHost and  -Dhttps.proxyPort ?

**Comment by open-gdsn** [comment]
Yes, sorry to not have explicitly added this. It was there when I initially started to write an issue but that was in the wrong place (base oxalis, not the AS4 extension)

**Comment by FrodeBjerkholt** [comment]
Can you provide more information? Do you have problems when using oxalis-standalone to send messages? It works for me when using -Dhttps.proxyHost and -Dhttps.proxyPort

**Comment by open-gdsn** [comment]
@FrodeBjerkholt : Sending to AS2 works and uses that proxy. Sending to AS4 does not (or at least did not, wes did not try updating the source of oxalis AS4 since december)

**Comment by FrodeBjerkholt** [comment]
Can you try upgrading to the latest RC, please?
