### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by artjomsk** [difi/Oxalis-AS4#46]
Question is related to https://github.com/difi/Oxalis-AS4/issues/32

I'm getting same exception when trying to send document through AS4 from RC10 to RC5.

As far as I understand it's because of commit 9c793d92c9f684ce415c17473b103b6c017d4154

So, it seems that latest RC is compatible with RC8 and newest. But we don't know what versions are in use on other end.

As well, I've tested that in opposite way - from RC5 to RC10 there is no any error. 

Because of the issue, for now, we cannot upgrade Oxalis-AS4 (it's simply scary)

**Comment by amaters-easy** [comment]
We have similar issues running RC10 trying to deliver to an AP running AS4 4.1.0-SNAPSHOT from February with the error: "The signature or decryption was invalid"
seems related

**Comment by artjomsk** [comment]
Our exception is absolutely same to #32 :

> {http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}X509Token: An incorrect X.509 Token Type is detected

In debug I've checked the exception is from X509TokenPolicyValidator.checkTokenType. Policy expects "X509KeyIdentifier", but got "SKIKeyIdentifier" as I remember.

**Comment by FrodeBjerkholt** [comment]
Remember that RCs are release candidates. Please try the new RC11.
