### ISSUE TITLE
MessageId in AS4 Module does not follow rfc2822 

### ISSUE THREAD

**Issue by jerouris** [difi/Oxalis-AS4#5]
The MessageID in AS4 must conform to RFC2822 ( `<ID>@<domain>` ). In current oxalis implementation the `@domain` is missing.

https://github.com/difi/Oxalis-AS4/blob/c6ac657a7582e772db15fe49ffd7ab931f73abbe/src/main/java/no/difi/oxalis/as4/outbound/As4Sender.java#L179-L181

**Comment by phax** [comment]
And you could make this method static :)

**Comment by jaflaten** [comment]
Thanks for reporting this issue. I've created a Jira-case which can be found here https://difino.atlassian.net/secure/RapidBoard.jspa?rapidView=39&projectKey=MOVE&modal=detail&selectedIssue=MOVE-1267

**Comment by clancger** [comment]
Hi all, 
Any expectation when this will be resolved please? It is preventing us (IBM) from doing AS4 certification

**Comment by jerouris** [comment]
Bug also affects receipt UUID: https://github.com/difi/Oxalis-AS4/blob/c6ac657a7582e772db15fe49ffd7ab931f73abbe/src/main/java/no/difi/oxalis/as4/inbound/As4InboundHandler.java#L181-L185

**Comment by FrodeBjerkholt** [comment]
Solved in 4.1.0-RC4
