### ISSUE TITLE
AS4 and Jetty

### ISSUE THREAD

**Issue by carher** [difi/Oxalis-AS4#54]
Oxalis 4.0.4
Jetty 9.4.7.v20170914
OpenJDK 1.8.0_232
Red Hat Linux

We use Jetty application server to run Oxalis, and are trying to figure out how to make the AS4 plugin work - without losing stdout logging.

The examples for how to install the plugin don't seem to apply to us. However, we tried to kind of replicate the Tomcat example, by putting the contents of the zip file under jetty/lib/ext. That by itself was not enough, so in the context-config.xml file we added <Set name="extraClasspath"> to the WebAppContext configuration, and pointed to oxalis-as4-4.1.0-SNAPSHOT.jar. This caused some troubles initially, until we moved oxalis-as4-4.1.0-SNAPSHOT.jar to a separate directory, i.e. not on the classpath initially, while its dependencies remained under jetty/lib/ext, and Oxalis itself together with dependencies under jetty/work. The remaining problem now was NoClassDefFound for SLF4J classes, so we copied a few SLF4J and Logback jar files to jetty/lib/ext. In this configuration the plugin works, and seems to run with no issues. Apart from the stdout logging now missing.

For Oxalis, we have a logback.xml defining what to log to which log files, but additionally Jetty would log the details our logback.xml don't cover to its own stdout file. What seems to happen when we add the log jar files to jetty/lib/ext, is that we somehow deactivate/disturb any structured logging to stdout. I.e. any LOG.INFO, LOG.WARN, LOG.ERROR statements in the libraries. The little logging that is defined as System.out.println in the libraries seems to still work, but that is all.

We have now tried numerous other ways of deploying the plugin, adding it to the classpath, setting up logging, but still no combination that completes everything: load the plugin, start with no errors, and write to stdout.

Do you have any suggestions? Are there other ways of deploying/activating the plugin, perhaps?

**Comment by FrodeBjerkholt** [comment]
I haven't tried Jetty myself, but I suggest you try the following: Add the AS4 Extension directly into the oxalis-dist/oxalis.-war project as a dependency and build a new WAR-file.

**Comment by carher** [comment]
Looks promising!
