### ISSUE TITLE
RC11 outbound needs truststore configuration?

### ISSUE THREAD

**Issue by tjeb** [difi/Oxalis-AS4#58]
With RC11, a truststore configuration setting is required for oxalis-standalone; and from the looks of it it only uses that setting as the truststore (as opposed to the older version, which extends the built-in truststore if the setting is used).

This appears to be new code, in OutboundMerlinProvider as well as InboundMerlinProvider; the latter one appears to have the old behaviour. From the looks of it, and a very quick test, the OutboundMerlinProvider could use the same code, or am I wrong here?

**Comment by FrodeBjerkholt** [comment]
Good point - I will look into it.

**Comment by FrodeBjerkholt** [comment]
You are right. I will do some more testing and most likely make a new RC later today.

**Comment by FrodeBjerkholt** [comment]
RC12 is now released with a fix.

**Comment by tjeb** [comment]
Thanks for the quick response!
