### ISSUE TITLE
AS4 Inbound handler does not check MessageID compliance accorting to rfc 2822

### ISSUE THREAD

**Issue by jerouris** [difi/Oxalis-AS4#6]
The AS4 Inbound handler does not check MessageID compliance when receiving a message, according to rfc 2822. 
https://github.com/difi/Oxalis-AS4/blob/c6ac657a7582e772db15fe49ffd7ab931f73abbe/src/main/java/no/difi/oxalis/as4/inbound/As4InboundHandler.java#L85

It also creates receipt messageIDs that are not compliant with rfc 2822 
see: https://github.com/difi/Oxalis-AS4/blob/c6ac657a7582e772db15fe49ffd7ab931f73abbe/src/main/java/no/difi/oxalis/as4/inbound/As4InboundHandler.java#L183

and https://github.com/difi/Oxalis-AS4/issues/5 for more information

**Comment by FrodeBjerkholt** [comment]
Solved in 4.1.0-RC4

**Comment by clancger** [comment]
Thanks for the help all
