### ISSUE TITLE
Multiple Trasport profiles

### ISSUE THREAD

**Issue by HarshaSuranjith** [difi/Oxalis-AS4#64]
Hi,

What's the behaviour if a particular process supports multiple transport profiles ?

How to set AS4 as default trasnport profile ?

#### TransmissionRequestBuilder.java [link](https://github.com/difi/oxalis/blob/master/oxalis-outbound/src/main/java/no/difi/oxalis/outbound/transmission/TransmissionRequestBuilder.java#L203)
```
if (isEndpointSuppliedByCaller() && isOverrideAllowed()) {
            log.warn("Endpoint was set by caller not retrieved from SMP, make sure this is intended behaviour.");
        } else {
            Endpoint endpoint = lookupService.lookup(effectiveStandardBusinessHeader.toVefa(), null);

            if (isEndpointSuppliedByCaller() && !this.endpoint.equals(endpoint)) {
                throw new IllegalStateException("You are not allowed to override the EndpointAddress from SMP.");
            }

            this.endpoint = endpoint;
        }
```

**Comment by FrodeBjerkholt** [comment]
This question is probably better answered in the Oxalis repository, but you can specify weights for different transport profiles to make Oxalis select the one you want. I.e.:

```properties
transport.as4_peppol_v1_to_v2_adapter = {
    profile: bdxr-transport-ebms3-as4-v1p0
    sender: oxalis-as4
    weight: 5000
}
```

**Comment by HarshaSuranjith** [comment]
Thanks, sorted out my issue.
