### ISSUE TITLE
Transport Profile for AS4 - PEPPOL Test Bed

### ISSUE THREAD

**Issue by skizub** [difi/Oxalis-AS4#67]
Hi,
Oxalis 4.1.0 - RC10

Successfully passed Inbound test from Test Bed - message was received by our AP.
But getting into troubles when trying to send amended file back using peppol-transport-as4-v2_0 profile.

After initial installation profile was not listed as available:
2020-01-29 11:55:01,100 INFO [no.difi.oxalis.commons.security.CertificateModule] Certificate issuer: CN=PEPPOL ACCESS POINT TEST CA - G2, OU=FOR TEST ONLY, O=OpenPEPPOL AISBL, C=BE 
2020-01-29 11:55:02,502 INFO [no.difi.vefa.peppol.security.ModeDetector] Detected mode: TEST 
2020-01-29 11:55:02,509 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] Prioritized list of transport profiles: 
2020-01-29 11:55:02,509 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0r1 
2020-01-29 11:55:02,509 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver2p0 
2020-01-29 11:55:02,509 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0 

and transmission was failing with a corresponding message (missing transport protocol).

When I explicitly added transport profile into oxalis.conf:
transport.peppol-transport-as4-v2_0 = {
      profile: peppol-transport-as4-v2_0
      sender: oxalis-as4
      weight: 5000
}

it's failing with following: 
"No implementation for no.difi.oxalis.api.outbound.MessageSender annotated with @com.google.inject.name.Named(value=oxalis-as4) was bound."

Could you please explain what is a correct approach? 
Is there a need to add transport  profile the way described (cannot find a corresponding advice in installation docs)? 
If yes - is it possible to see an example of such profile for peppol-transport-as4-v2_0?

**Comment by FrodeBjerkholt** [comment]
Please use the latest 4.1.1 release, since RC10 is only a release candidate (with known bugs)

There shouldn't be necessary to explicitly add the as4 transport profile in oxalis.conf.

I see from the attached log file, that the "Prioritized list of transport profiles" do not include the peppol-transport-as4-v2_0.

If the AS4 extension is correctly installed, then you should see:

```text
2020-01-29 13:37:00,345 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] Prioritized list of transport profiles:
2020-01-29 13:37:00,345 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => peppol-transport-as4-v2_0
2020-01-29 13:37:00,345 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0r1
2020-01-29 13:37:00,345 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver2p0
2020-01-29 13:37:00,345 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0
``` 

Please follow the directions found [here](https://github.com/difi/Oxalis-AS4/blob/master/docs/installation/standalone.md).

**Comment by skizub** [comment]
Thank you. Two  question to clarify. 

As 4.1.1 release is available only for AS4 component: https://github.com/difi/Oxalis-AS4/releases
is it safe to assume it can be used together with module standalone and distribution v 4.1.0 - located here: https://github.com/difi/oxalis/releases
?

Looks like main issue is related to component installation. Can you point out to the correct version please? 
I was trying to follow for standalone: https://github.com/difi/Oxalis-AS4/blob/master/docs/installation/standalone.md, 
For server side: https://github.com/difi/Oxalis-AS4/blob/master/docs/installation/server.md

**Comment by FrodeBjerkholt** [comment]
Yes the 4.1.1 release is compatible with Oxalis 4.1.0. Just place all the files in oxalis-as4-4.1.1-dist.zip
in the extension folder.

**Comment by FrodeBjerkholt** [comment]
I see the documentation needs to be updated to reference the new release.

**Comment by skizub** [comment]
**Yes the 4.1.1 release is compatible with Oxalis 4.1.0. Just place all the files in oxalis-as4-4.1.1-dist.zip
in the extension folder.**
Thank you

**Comment by skizub** [comment]
**I see the documentation needs to be updated to reference the new release.**

Is it possible to upload an updated version?

**Comment by FrodeBjerkholt** [comment]
I have now updated the documentation with the correct version.

**Comment by skizub** [comment]
Thank you

**Comment by skizub** [comment]
Frode, still no luck I'm afraid. Assuming problem is with folder structures for AS4 extension. Is it possible to share screenshots showing an example of correct folder structure? Ones meant to be here( as 'alt text' links):
https://github.com/difi/Oxalis-AS4/blob/master/docs/installation/tomcat.md 

are not available on Github.

**Comment by FrodeBjerkholt** [comment]
I have now fixed the image paths in the Tomcat documentation.

**Comment by skizub** [comment]
Thank you - tomcat installation is more clear now and works (receiving).
OXALIS_HOME directory is defined as /opt/oxalis. This is a place where oxalis.war file is located

But still there are problems with sending. I followed  this link to configure oxalis standalone https://github.com/difi/Oxalis-AS4/blob/master/docs/installation/standalone.md

Screenshot below is showing folder structures created as a result:
![oxalis](https://user-images.githubusercontent.com/37209717/73464973-fc3d3a00-437f-11ea-96dc-de5c1d908b77.png)

But when I'm trying to send from /opt/oxalis - getting same error as per following screenshot. It seems to completely ignore AS4 component:
![oxalis_failure](https://user-images.githubusercontent.com/37209717/73465358-91403300-4380-11ea-93dd-a97ec882fec1.png)

Can you advise or explain the logic standalone module is using to add AS4?

**Comment by FrodeBjerkholt** [comment]
Can you include the complete command line you are using?

**Comment by FrodeBjerkholt** [comment]
Use a command line similar to this:

java -DOXALIS_HOME=/c/dev/peppoltest/.oxalis \ -classpath "standalone/*;as4/*" \ eu.sendregning.oxalis.Main \ -f the_altered_file.xml

Here it is the classpath argument that includes the as4 module.

**Comment by FrodeBjerkholt** [comment]
One other thing. I prefer to keep the inbound and outbound applications seperate from each other.

**Comment by skizub** [comment]
Thank you. I figured out what was wrong. Problem was that we were using "java -jar oxalis-standalone.jar" approach mainly because of operational compatibility with previous (AS2) version of Oxalis. When I changed it to Linux equivalent of the command above:
**java -DOXALIS_HOME=/opt/oxalis -cp ".:standalone/*:as4/*" eu.sendregning.oxalis.Main  -f $FILE2SEND**
it started to use as4 extension and transmission to PEPPOL TestBed was successful.
Does it mean that invoking oxalis-standalone.jar vs invoking Main class inside thatJar is not the same thing anymore and 2nd approach must be used going forward?

**Comment by FrodeBjerkholt** [comment]
It important that your current directory is in the oxalis-standalone-as4

Can you try with -classpath "standalone/*;as4/*", please?

**Comment by skizub** [comment]
I see your point.
Of course this line fails,
java -DOXALIS_HOME=/opt/oxalis -cp ".:standalone/:as4/ " eu.sendregning.oxalis.Main -f $FILE2SEND
with a message "Could not find or load main class eu.sendregning.oxalis.Main"


correct command is: 
java -DOXALIS_HOME=/opt/oxalis -cp ".:standalone/* :as4/* " eu.sendregning.oxalis.Main -f $FILE2SEND

looks like asteriks (*) were removed from my original message as a part of formatting. 
I've added space after each * now so it's displaying correctly.

**Comment by skizub** [comment]
Thank you very much for your help.
Can you just confirm we should call eu.sendregning.oxalis.Main in future versions of Oxalis?

Feel free to close this issue after that.

**Comment by FrodeBjerkholt** [comment]
There is a lot of overhead starting the eu.sendregning.oxalis.Main.
If you are going to send a lot of messages, then you should implement your own sending application based on the Transmitter interface.

**Comment by skizub** [comment]
Thank you - we'll have a look at this option.
