### ISSUE TITLE
Is there possibility of storing encrypted keys or not to use oxalis.conf at all?

### ISSUE THREAD

**Issue by saneokv** [difi/Oxalis-AS4#71]
Hi @difi. I tried to use oxalis and oxalis-as4 for sending some documents to peppol and it works in the way you specified in the documentation. Actually my problem is I don't want to store keystore password and alias password in oxalis.conf as it is specified, as I have it encrypted in other properties file and would like just to send it to oxalis. Is there any possibility of not using oxalis.conf at all and to send as some properties maybe when creating OxalisOutboundComponent? If not, will be this functionality in future?

**Comment by FrodeBjerkholt** [comment]
Can ask this question at the oxalis repo, please?
