### ISSUE TITLE
Where to find the standalone.jar for AS4?

### ISSUE THREAD

**Issue by CorZijlstra** [difi/Oxalis-AS4#73]
Does anyone know where to find the download for the Oxalis-Standalone.jar for AS4.

We found the 4.1.0 version on Maven Central but that only support AS2?

Can someone provide us with a download URL please?

**Comment by FrodeBjerkholt** [comment]
The Oxalis-AS4 is an extension to Oxalis, so the intention is to use the standard oxalis-standalone distribution and add AS4 as an extension to this. You can find the Oxalis-AS4 files here: https://github.com/difi/Oxalis-AS4/releases

Follow this description: https://github.com/difi/Oxalis-AS4/blob/master/docs/installation/standalone.md
