### ISSUE TITLE
Mismatch of the digest of the attachment in the signature

### ISSUE THREAD

**Issue by descala** [difi/Oxalis-AS4#76]
In the outgoing pipeline, encryption adds a "Content-ID" header before the compressed payload. The consequence for the receiver is that it can not check the signature, because the digest with the "Content-ID" is obviously not the same as the one without it.

It may be caused by a miss-configuration of [the 'complete' parameter in setupAttachmentEncryptionStream](https://github.com/apache/ws-wss4j/blob/420947d684383aeed40a2e41717da6197fb1d9dd/ws-security-common/src/main/java/org/apache/wss4j/common/util/AttachmentUtils.java#L564), part of Apache WebServices - WSS4J. This is a blind shot. I am not familiar with this Java code.

We have stumbled with this issue receiving from the PEPPOL Testbed.

**Comment by FrodeBjerkholt** [comment]
I see that the Transform:Algorithm is set to Attachment-Content-Signature-Transform 
and therefore the Content-ID shouldn't have been added. I need to investigate why WSS4J is doing this to verify if this is a bug or not.

I also see that the reference AS4 implementation Domibus also are using the the same version of WSS4J, but I am not sure if Domibus has the same problem? The problem can also be a result of some CXF issue. Domibus uses CXF 3.2.6 - Oxalis is using CXF 3.3.5.

**Comment by FrodeBjerkholt** [comment]
After debugging WSS4J I see that I can avoid the "complete"-block by setting         
message.put(USE_ATTACHMENT_ENCRYPTION_CONTENT_ONLY_TRANSFORM, true);

**Comment by FrodeBjerkholt** [comment]
First tests shows that the change work with oxalis-as4 4.1.2. I need do some thorough testing before I can make a new release, but I think it is promising.

**Comment by FrodeBjerkholt** [comment]
I have now released 4.1.3 that hopefully solves the issue. I have also sent an email to PEPPOL urging for an update of the Oxalis AS4 extension in the OpenPEPPOL Test bed. I will notify here as soon as I get an upgrade confirmation from them.

**Comment by FrodeBjerkholt** [comment]
The testbed is updated, so I close the issue. We will try to get everyone using Oxalis to upgrade to the latest AS4 release.
