### ISSUE TITLE
Timeline for deployment of 4.1.0-RC4 to testbed?

### ISSUE THREAD

**Issue by clancger** [difi/Oxalis-AS4#8]
I see the RFC 2822 issue has now been resolved in 4.1.0-RC4. 
Can you please advise when this will be deployed on the testbed?

I see the current release is version.oxalis: 4.0.3-SNAPSHOT 
https://test-aksesspunkt.difi.no/status

Thanks
Ger

**Comment by klakegg** [comment]
Version of AS4 plugin is not connected to version of Oxalis.
