### ISSUE TITLE
Thank you Difi

### ISSUE THREAD

**Issue by ri4a** [difi/Oxalis-AS4#82]
A big thanks to Difi for Oxalis and the new AS4 module. It has been tough at some point, but since Frode Bjerkholt started working on this project it has really been flying. I realize others have made significant contributions, but well done Frode!

Please :thumbsup: if you agree!

Michael from Storecove

**Comment by FrodeBjerkholt** [comment]
Thank you for the confidence😀 It is an exciting project to work on.

**Comment by aaron-kumar** [comment]
Fully agree with you @ri4a (Michael). I hope, DIFI(Digdir) find guys like @FrodeBjerkholt to work on/maintain other repositories/projects.

**Comment by JesperLarsenOO** [comment]
Big kudos from me aswell.. We see tremendous progress!
