### ISSUE TITLE
Testbed sending issue on 4.1.3

### ISSUE THREAD

**Issue by RvanMaarenApro** [difi/Oxalis-AS4#83]
When using the testbed, receiving is fine. Sending however results in the following error :
2020-02-07 10:34:00,710  ERROR [org.apache.cxf.ws.policy.PolicyVerificationInInterceptor] Inbound policy verification failed: These policy alternatives can not be satisfied:
{http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}SignedParts: Soap Body is not SIGNED
2020-02-07 10:34:00,714  WARN [org.apache.cxf.phase.PhaseInterceptorChain] Interceptor for {oxalis.difi.no/}outbound-service#{http://cxf.apache.org/jaxws/dispatch}Invoke has thrown exception, unwinding now
org.apache.cxf.ws.policy.PolicyException: These policy alternatives can not be satisfied:
{http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}SignedParts: Soap Body is not SIGNED

Any thoughts ?

Regards,

Richard

**Comment by FrodeBjerkholt** [comment]
Can you show me the command line you are using when sending? And the contents of your oxalis.conf?

**Comment by FrodeBjerkholt** [comment]
Just to be sure I just performed successfully the two first test in the Conformance/onboarding test suite. Version 1.0

**Comment by RvanMaarenApro** [comment]
Found the cause of this, in my oxalis conf the #oxalis.as4.type=cef-connectivity line was still active. My previous version fo AS4 was RC11 which had no problems with that.

Now I was able to send also.

**Comment by FrodeBjerkholt** [comment]
Great that you found it out. The cef-connectivity type enforces a different security policy.
