### ISSUE TITLE
cxf tmp files not deleted

### ISSUE THREAD

**Issue by olauspet** [difi/Oxalis-AS4#88]
We have noticed in the oxalis-inbound that it creates cxf tmp files in the temp directory. These files are never deleted, and we end up with disk space issues after a while.
oxalis 4.1.1
oxalis-as4 4.1.3
running on tomcat 9

**Comment by FrodeBjerkholt** [comment]
I will look into it at Thursday.

**Comment by olauspet** [comment]
It seems related to receiving large files, containing embedded attachments.

**Comment by FrodeBjerkholt** [comment]
I am working on a solution with a scheduled job that removes those temporary files after a certain amount of time.  Most likely there will be a release tomorrow.

**Comment by FrodeBjerkholt** [comment]
My first attempts with a job that removes the temporary files has problems because of file locks. I need to investigate further.

**Comment by olauspet** [comment]
Could it be due to missing close of InputStreams? What I understand, the cxf tmp files are created for larger payloads and would be deleted when all references are closed.
Example:
As4InboundHandler.persistPayload is exhausting the input stream but not closing it?

**Comment by FrodeBjerkholt** [comment]
Yes, I agree. I have already tried closing, but it did not help. But I will see if I can dig some more.

**Comment by FrodeBjerkholt** [comment]
I have found a solution and will most likely make a new release tomorrow.

**Comment by FrodeBjerkholt** [comment]
Resolved in 4.1.6
