### ISSUE TITLE
Another large file issue..

### ISSUE THREAD

**Issue by hjkjorstad** [difi/Oxalis-AS4#95]
One of our outbound services tried to deliver at file with size  = 29323199 (bytes) via AS4. This trial lead to  the following Exception:

...
 org.apache.cxf.interceptor.Fault: Could not send Message.
fms-ap-outbound-4.1.c213gyc6fxa2@er-fmsweb06.os.eon.no    |     at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:67)
fms-ap-outbound-4.1.c213gyc6fxa2@er-fmsweb06.os.eon.no    |     at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
....

and 

...

Caused by: org.apache.cxf.transport.http.HTTPException: HTTP response '504: Gateway Time-out' when communicating with ...
...

The communication starts at: 2020-02-19 17:41:52
And the Exception occurs at : 2020-02-19 17:43:00

We have configure: oxalis.http.timeout.read = 600000

It seems like this is not involved in this kind of timeout.

We were able to deliver the same message (later) with a manual fall-back to AS2 v1 (for this specific destination/endpoint - still supporting AS2v1)..

**Comment by FrodeBjerkholt** [comment]
It seems like the receiving part timed out. I noticed that the complete attachment is temporarly stored in a byte array. I will try to change that to avoid memory problems, that might lead to slow performance. The main focus in the comming days, will be the large file issues and the related tmp file issue.

**Comment by FrodeBjerkholt** [comment]
Just released 4.1.7 with a large file fix.
